export interface Paper {
  id?: string; // optional on creation
  title: string;
  author: string;
  domain: string;  // must match DOMAINS in frontend
  stage: string;   // must match STAGES in frontend
  citations: number;
  impact: string;  // must match IMPACTS in frontend
  date: string;    // ISO date string
  created_at?: string; // auto generated by supabase
}